# graph generator config

output = 'generated_graph.json'

[count]
zone = 3
entity = 100
relation = 200

[share.type]
provider = 1.0
space = 4.0
group = 16.0
user = 64.0

[share.relation]
space_provider = 10.0
group_space = 10.0
group_group = 10.0
user_group = 20.0
user_space = 10.0

[prob.relation]
inter_zone = 0.10

# operation generator config

#steps.relation.deletion.prob = 0.05
#steps.relation.change.prob = 0.1
