# graph generator config

count.zone = 3
count.entity = 100
count.relation = 200

type.provider.share = 1
type.space.share = 4
type.group.share = 16
type.user.share = 64

relation.space_provider.share = 10
relation.group_space.share = 10
relation.group_group.share = 10
relation.user_group.share = 20
relation.user_space.share = 10

relation.inter_zone.prob = 0.10

# operation generator config

steps.relation.deletion.prob = 0.05
steps.relation.change.prob = 0.1
