version: '3'
services:
  zone0:
    build: .
    command: server
    environment:
      ZONE_ID: zone0
    networks:
      intranet:
    ports:
      - 8080:80
      - 8780:8080

  zone1:
    build: .
    command: server
    environment:
      ZONE_ID: zone1
    networks:
      intranet:
    ports:
      - 8081:80
      - 8781:8080

  tester:
    build: .
    command: test zone0
    environment:
      ALL_ZONES: zone0,zone1
      GRAPH_PATH: graph.json
    networks:
      intranet:
    ports:
      - 8789:8080
    depends_on:
      - zone0
      - zone1

  client:
    build: .
    command: client
    stdin_open: true
    tty: true
    networks:
      intranet:

networks:
  intranet:
